### PR TITLE
Create 2022-01-20-seminar.tweet

### PR DESCRIPTION
**Pull request by lucaferranti**

### CODE REVIEW

**Review by annefou — APPROVED** [review]
Thank you so much for preparing this tweet.

**Comment by PatricHolmvall** [comment]
@lucaferranti is it just me, or was the tweet never published?

**Comment by annefou** [comment]
True. I am not sure why.

**Comment by lucaferranti** [comment]
whaat? did I do something wrong? 😨

**Comment by lucaferranti** [comment]
ok I think I got it, when I created the tweet, I accidentally deleted the `tweets/` from the filename, so the file was saved in the repository root and not in the `tweets` folder.

**Pull request merged**
