### PR TITLE
Announce the Nordic-RSE 2021 unconference

### LINKED ISSUE #15: Announce Nordic-RSE 2021 unconference
Send out a tweet announcing the Nordic-RSE 2021 unconference.

### PR DESCRIPTION
**Pull request by PatricHolmvall**
Closes #15 

Feel free to edit, improve or completely rewrite.

### CODE REVIEW

**Review by bast — CHANGES_REQUESTED** [review]
Slightly too long but that is not a problem.
Bigger problem: the Twitter preview still shows image with the two speakers from last year's conference so we need to change the Twitter preview.

**Comment by bast** [comment]
The "requested changes" does not mean Patric needs to change but somebody needs to fix it before this tweet goes out.

**Comment by PatricHolmvall** [comment]
> The "requested changes" does not mean Patric needs to change but somebody needs to fix it before this tweet goes out.

Should we perhaps create a similar image for this unconference? That probably relies on finding already the invited speakers, which might happen much closer to the event itself?

**Comment by bast** [comment]
Preview image is a good idea. It does not have to contain speakers. So I would not wait until we have a program.

**Comment by bast** [comment]
I will take care of removing current Twitter card. It's a problem. Every time anybody tweets about our website, it will show the speakers from last year.

**Comment by PatricHolmvall** [comment]
Here is another suggestion for the tweet, based on an early suggestion by Jarno:
"We are organizing an online unconference June 29-30. This is a lightweight get-together where you create the agenda. Check out the event website at nordic-rse.org/events/2021-online-unconference/ and add your ideas to the agenda."

Maybe this is better? What I would like to add to this is some tags, and at least something on what the topic is (some people seeing this announcement might not know who "we" are), without constraining the contributions too much.

**Comment by samumantha** [comment]
A bit different suggestion based on suggestions above:  "#NordicRSE invite everyone interested in #RSE activities to join and shape the agenda of the first NordicRSE unconference  on June 29+30. Submit your proposals and find more infos on our website: nordic-rse.org/events/2021-online-unconference/" #gettogether #birdsofafeather"

**Comment by PatricHolmvall** [comment]
> A bit different suggestion based on suggestions above: "#NordicRSE invite everyone interested in #RSE activities to join and shape the agenda of the first NordicRSE unconference on June 29+30. Submit your proposals and find more infos on our website: nordic-rse.org/events/2021-online-unconference/" #gettogether #birdsofafeather"

I think that this is an improvement, thank you! A question that comes to mind is if we want to disseminate mainly within the RSE bubble, or should people who are unfamiliar with the RSE term be able to get the gist of it? My first tweet suggestion became too long because I tried to address this.

**Comment by samumantha** [comment]
Ah true, makes totally sense. 
Following is a guess, and a suggestion based on that guess: followers of Nordic RSE are in the bubble. People that do not follow are not. They will only (?) see the post when retweeted (?) so we could also use main parts of your text for retweeting?
But I am also fully ok with forgetting about my suggestion and just going with your original suggestion shortened to eg this: 'Developing software or doing data analysis for research? Or interested in these topics? Join the online "unconference" of the Nordic Research Software Engineer initiative, 29-30.6: nordic-rse.org/events/2021-online-unconference/ #RSE #research #softwaredevelopment #dataanalysis'

**Comment by PatricHolmvall** [comment]
> Ah true, makes totally sense.
> Following is a guess, and a suggestion based on that guess: followers of Nordic RSE are in the bubble. People that do not follow are not. They will only (?) see the post when retweeted (?) so we could also use main parts of your text for retweeting?
> But I am also fully ok with forgetting about my suggestion and just going with your original suggestion shortened to eg this: 'Developing software or doing data analysis for research? Or interested in these topics? Join the online "unconference" of the Nordic Research Software Engineer initiative, 29-30.6: nordic-rse.org/events/2021-online-unconference/ #RSE #research #softwaredevelopment #dataanalysis'

I think you are right that it's mainly people in the bubble who will see this. Is it wishful thinking to hope otherwise? Maybe it's the bubble we want to reach anyway? Thank you for your new suggestion - now we have two good options that we can use depending on the target audience. :)

**Comment by bast** [comment]
Also `#RSEng` seems to be the hashtag. `#RSE` is often used for something else. I like both. I also liked that submitting a proposal is mentioned. Maybe "Submit a (lightweight) proposal". But yeah, we will only reach the bubble but then hopefully people will retweet and re-post.

**Comment by PatricHolmvall** [comment]
Amended: tried to blend all the suggestions, based on Samanthas draft.

**Review by samumantha — APPROVED** [review]
Great! The first #RSE could also be #RSEng and therefore leave out the second #RSEng, but both work.

Thanks :)

**Comment by PatricHolmvall** [comment]
> Great! The first #RSE could also be #RSEng and therefore leave out the second #RSEng, but both work.
> 
> Thanks :)

I removed the #RSE tag in favor of explaining what RSE means. The amended suggestion incorporates all the feedback so far, into one of Samanthas drafts. I think it could be ready to be tweeted, but perhaps we should try to solve [the PR](https://github.com/nordic-rse/nordic-rse.github.io/pull/222) of @lucaferranti first, so that the unconference page is tidy when people click the link.

**Comment by bast** [comment]
Two more things:
- there needs to be an https:// in front of the link, otherwise Twitter does not seem to preview it
- the preview does not seem to show the new image. perhaps it hasn't been added to the repo yet?

**Comment by bast** [comment]
This needs to be fixed first: https://github.com/nordic-rse/nordic-rse.github.io/blob/ce426f369279aaa648deaf19f432c83fd178ec44/templates/base.html#L21

**Comment by PatricHolmvall** [comment]
> This needs to be fixed first: https://github.com/nordic-rse/nordic-rse.github.io/blob/ce426f369279aaa648deaf19f432c83fd178ec44/templates/base.html#L21

What exactly needs to be fixed there? It needs to be changed to the new image that Samantha made?

**Comment by PatricHolmvall** [comment]
> Two more things:
> 
> * there needs to be an https:// in front of the link, otherwise Twitter does not seem to preview it
> * the preview does not seem to show the new image. perhaps it hasn't been added to the repo yet?

Amended the first point!

**Comment by PatricHolmvall** [comment]
> > This needs to be fixed first: https://github.com/nordic-rse/nordic-rse.github.io/blob/ce426f369279aaa648deaf19f432c83fd178ec44/templates/base.html#L21
> 
> What exactly needs to be fixed there? It needs to be changed to the new image that Samantha made?

Maybe also here?

https://github.com/nordic-rse/nordic-rse.github.io/blob/ce426f369279aaa648deaf19f432c83fd178ec44/templates/base.html#L31

**Comment by bast** [comment]
I am fixing the other point.

**Comment by bast** [comment]
> I am fixing the other point.

... but where is the new image?

**Comment by PatricHolmvall** [comment]
> > I am fixing the other point.
> 
> ... but where is the new image?

Oh, I just sent in this PR: https://github.com/nordic-rse/nordic-rse.github.io/pull/228

Please edit/discard that as you see fit.

**Comment by PatricHolmvall** [comment]
> > > I am fixing the other point.
> > 
> > 
> > ... but where is the new image?
> 
> Oh, I just sent in this PR: [nordic-rse/nordic-rse.github.io#228](https://github.com/nordic-rse/nordic-rse.github.io/pull/228)
> 
> Please edit/discard that as you see fit.

Great, I just realized that my linter changed the format of the file. Sorry!

**Comment by bast** [comment]
Testing preview ...

**Review by bast — APPROVED** [review]
I think now it should work.

**Comment by PatricHolmvall** [comment]
> I think now it should work.

Great - maybe we send it out today or early tomorrow, what do you think? I'm trying to figure out how to check the preview. I'm looking in the pipeline and the instructions, but maybe I'm wrongly expecting to be able to see the whole tweet/image thumbnail preview?

**Comment by bast** [comment]
What I did was to paste the text into my own Twitter and not send it but only to check how it previews.
Also checking this for link previews: https://cards-dev.twitter.com/validator

**Comment by bast** [comment]
It's out. Thanks a lot for all the drafting effort!

**Pull request merged**
