### PR TITLE
moved tweet file to right place

### PR DESCRIPTION
**Pull request by lucaferranti**

### CODE REVIEW

**Comment by lucaferranti** [comment]
does this fix the problem?

**Comment by PatricHolmvall** [comment]
> does this fix the problem?

Yeah I think this should do it. Let's try - just merge it when you're ready. :)

**Review by annefou — APPROVED** [review]

**Review by PatricHolmvall — APPROVED** [review]

**Comment by lucaferranti** [comment]
still didn't work? :o

**Comment by PatricHolmvall** [comment]
> still didn't work? :o

Hmmm... did you check that the character count was smaller than the maximum allowed for a tweet?

**Comment by annefou** [comment]
Yes I think it is too long. This would fit:

Do you use #RLang in your research? Would you like to learn how to create and distribute packages?  #NordicRSE seminar series is inviting @DrMowinckels to give a talk "Developing and distributing in-house R-packages" on Thursday 20 January at 13:00 CET .

https://nordic-rse.org/events/seminar-series/#january-2022-developing-and-distributing-in-house-r-packages

**Comment by lucaferranti** [comment]
the characters length limit should be checked by the CI? @rkdarst guessed on zulip that this failed because it just renamed a file and the CI is "smart" enough not to tweet if you just rename a file (avoid accidental retweet etc.) summa summarum, I guess a new PR is to be open

**Pull request merged**
